### ISSUE TITLE
Moving average exponential results are not matching with the zerodha kite connect output

### ISSUE THREAD

**Issue by Prchakr** [arkochhar/Technical-Indicators#11]
Moving average exponential results are not matching with the zerodha kite connect output

I have tried 20 days EMA base field as Close and results are having gap

**Comment by Prchakr** [comment]
Never mind issue is on my side while calling ema i set alpha as false which gave unexpected result
After setting up true received the expected result as like in zerodha kite

**Comment by arkochhar** [comment]
Thanks for your inputs
