### ISSUE TITLE
Make supertrend calculation faster

### ISSUE THREAD

**Issue by ChillarAnand** [arkochhar/Technical-Indicators#2]
@arkochhar  Thank you for writing supertrend calcuator in Python.

Once supertrend is calculated and stored in dataframe, if new data comes, we should be able to append the new data to existing dataframe and supertrend should be calculated to only new data but not for entire data.

**Comment by arkochhar** [comment]
@ChillarAnand the pandas calculations are so fast that it doesn't make any sense to complicate the logic. Moreover supertrend computations need to consider smooth ATR for previous n values.  What I can suggest is that you concatenate the new data to the existing dataframe and then recompute the supertrend. Its very fast with pandas. I have done the same in my code that calls supertrend function.
